### ISSUE TITLE
Mekanism Cables causing a crash when broken with a Tinkers pickaxe.

### ISSUE THREAD

**Issue by pyure** [Master0r0/Ultima-Techno-Magicka---Modpack#1]
Minecraft instantly crashes to desktop when attempting to break Mekanism cables with a pickaxe.

Reproduced with Tinkers and Vanilla pickaxes.

Attempted fix (did not work)
* Upgraded all Mekanism mods.

Probably an RF Api issue.

**Comment by pyure** [comment]
Workaround: updating all mods in the pack fixes the issue.  I'm not certain which specific update corrected it unfortunately.

**Comment by Master0r0** [comment]
Ok, I will be posting a pack update soonish
